BugFix: Fix Converting null literal in ServiceCollectionExtensions
project-studying-dotnet/Streetcode-Admin pull request #118
Opened 2024-02-07 23:00 UTC by SvyatoS1

2024-02-08 06:23 UTC, MrVenik reviewed
Maybe using null checking and throwing another exception with message that would describe what exactly is going wrong - would be more preferable ?

2024-02-08 07:04 UTC, SvyatoS1 commented
> Maybe using null checking and throwing another exception with message that would describe what exactly is going wrong - would be more preferable ?

Okay, i'll fix that. I just thinking about in how many cases 'DefaultConnection' will be null, and to simpify use !, but we can also implement null error handling.

2024-02-08 09:28 UTC, MrVenik commented
> > Maybe using null checking and throwing another exception with message that would describe what exactly is going wrong - would be more preferable ?
> 
> Okay, i'll fix that. I just thinking about in how many cases 'DefaultConnection' will be null, and to simpify use !, but we can also implement null error handling.

Or just check if connection string is null and throw exception.
Only if user forgot to add connection strings to user secrets file can lead us to this exception, the exception would not be handled at all, because it is critical error.

2024-02-08 15:16 UTC, MrVenik requested changes

2024-02-08 15:16 UTC, MrVenik commented on Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
> +using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;
Is this using needed ?

2024-02-08 15:22 UTC, SvyatoS1 commented on Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
> +using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;
Maybe not, it was added automatically, in last commit i remove it.

2024-02-08 15:54 UTC, MrVenik approved these changes

2024-02-10 11:13 UTC, Skilskyi approved these changes

2024-02-12 07:09 UTC, merged