Added update logic art_galery
project-studying-dotnet/Streetcode-Admin pull request #120
Opened 2024-02-08 18:54 UTC by Skilskyi

2024-02-08 23:45 UTC, MrVenik requested changes

2024-02-08 23:45 UTC, MrVenik commented on Streetcode/Streetcode.BLL/DTO/Media/Art/ArtUpdateDto.cs
> +namespace Streetcode.BLL.DTO.Media.Create
File-scoped namespaces please (?)

2024-02-08 23:45 UTC, MrVenik commented on Streetcode/Streetcode.BLL/DTO/Media/Art/ArtUpdateDto.cs
> +    public class ArtUpdateDTO
If this is an request - you can make it record

2024-02-08 23:45 UTC, MrVenik commented on Streetcode/Streetcode.BLL/MediatR/Media/Art/Update/UpdateArtErrorMessages.cs
> +public static class UpdateErrorMessages
Use Resource files errors messages

2024-02-08 23:45 UTC, MrVenik commented on Streetcode/Streetcode.BLL/MediatR/Media/Art/Update/UpdateArtHandler.cs
> +    private readonly ILoggerService _logger;
Blank lines between fields and constructors

2024-02-08 23:45 UTC, MrVenik commented on Streetcode/Streetcode.BLL/MediatR/Media/Art/Update/UpdateArtHandler.cs
> +    }
same here

2024-02-08 23:45 UTC, MrVenik commented on Streetcode/Streetcode.BLL/MediatR/Media/Art/Update/UpdateArtHandler.cs
> +        if (existingArt is null)
if existingArt is never used, maybe it is better to left this check for validator (it is for an future takss)

2024-02-08 23:45 UTC, MrVenik commented on Streetcode/Streetcode.WebApi/Controllers/Media/Images/ArtController.cs
> +    public async Task<IActionResult> Update([FromRoute] int id, [FromBody] ArtUpdateDTO art)
You can use one request from the form (cause it is an http request from the form)
Why you need this is froum the route ?

2024-02-12 07:19 UTC, SvyatoS1 approved these changes

2024-02-12 08:42 UTC, Skilskyi commented
-Removed redundant null check
-Transfered HandlerTest file in correct folder

2024-02-12 09:14 UTC, MrVenik commented
Wait untill #132 would be merged, then pull from `story/at_gallery`

2024-02-12 09:54 UTC, Skilskyi commented
-Fixed issues with ArtEntity

2024-02-12 10:00 UTC, MrVenik approved these changes
Great job!

2024-02-12 10:09 UTC, merged