Global exception handling middleware
project-studying-dotnet/Streetcode-Admin pull request #128
Opened 2024-02-10 14:46 UTC by MishaPolishchuk

Added global exception handling middleware

2024-02-10 15:39 UTC, MrVenik requested changes

2024-02-10 15:39 UTC, MrVenik commented on Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
> +    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
Are you sure that we need `FluentValidation.DependencyInjectionExtensions` package in `Streetcode.BLL` project ?

2024-02-10 15:39 UTC, MrVenik commented on Streetcode/Streetcode.WebApi/Middlewares/ExceptionHandlingMiddleware.cs
> +            _logger.LogGlobalError(excInfoMsg);
Is validation exceptions should be logged ?

2024-02-10 15:39 UTC, MrVenik commented on Streetcode/Streetcode.WebApi/Middlewares/ExceptionHandlingMiddleware.cs
> +using Streetcode.BLL.Exceptions;
'Exceptions' does not exist in the namespace 'Streetcode.BLL' ?

2024-02-12 07:10 UTC, MishaPolishchuk commented on Streetcode/Streetcode.WebApi/Middlewares/ExceptionHandlingMiddleware.cs
> +            _logger.LogGlobalError(excInfoMsg);
It`s completely OK practice

2024-02-12 07:12 UTC, MishaPolishchuk commented on Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
> +    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
Seeped through. Will removed further

2024-02-12 09:53 UTC, SvyatoS1 approved these changes

2024-02-12 12:51 UTC, MrVenik approved these changes

2024-02-12 20:29 UTC, merged