Add test News Handler
project-studying-dotnet/Streetcode-Admin pull request #14
Opened 2024-01-25 18:48 UTC by Skilskyi

2024-01-26 14:17 UTC, MrVenik commented
- Remove changes of `Program.cs` and `appsettings`
- Try to use file-scoped namespaces
- Some of mock fields can be marked as readonly
- Not interpolated strings can be marked as const
- Try to add blank lines between methods
- Some of the private methods should have better name (`GetAllNewsAsync(IEnumerable<DAL.Entities.News.News> newsList` is used for setup mocks but name is not meaningfull))

2024-01-26 14:25 UTC, MrVenik requested changes
- Remove changes of `Program.cs` and `appsettings`
- Try to use file-scoped namespaces
- Some of mock fields can be marked as readonly
- Not interpolated strings can be marked as const
- Try to add blank lines between methods
- Some of the private methods should have better name (`GetAllNewsAsync(IEnumerable<DAL.Entities.News.News> newsList` is used for setup mocks but name is not meaningfull))

2024-01-26 17:10 UTC, MrVenik approved these changes

2024-01-28 21:25 UTC, SvyatoS1 approved these changes

2024-01-29 07:22 UTC, merged