Feature: Add validation for delete fact
project-studying-dotnet/Streetcode-Admin pull request #141
Opened 2024-02-15 23:42 UTC by SvyatoS1

Added validation for delete fact

2024-02-16 07:31 UTC, MrVenik requested changes

2024-02-16 07:31 UTC, MrVenik commented on Streetcode/Streetcode.BLL/MediatR/Streetcode/Fact/Delete/DeleteFactValidation.cs
> +            .WithMessage(DeleteFactErrors.DeleteFactIdNullError);
Dpn't forget to check existence of id and check that id is greater than zero

2024-02-17 12:16 UTC, MishaPolishchuk commented on Streetcode/Streetcode.BLL/MediatR/Streetcode/Fact/Delete/DeleteFactValidation.cs
> +                    CannotFindEntityErrors.CannotFindFactById, dfc.Request.FactId));
There was an agreement, that we provide such validation types as DB checks in the extension method ( MediatrCommandsQueriesValidatorExtension.cs)

2024-02-17 12:50 UTC, MrVenik commented on Streetcode/Streetcode.BLL/MediatR/Streetcode/Fact/Delete/DeleteFactValidation.cs
> +                    CannotFindEntityErrors.CannotFindFactById, dfc.Request.FactId));
> There was an agreement, that we provide such validation types as DB checks in the extension method ( MediatrCommandsQueriesValidatorExtension.cs)

Are you sure that this is good idea ? It would lead us to hilariously big static class `MediatrCommandsQueriesValidatorExtension.cs`
If it is simple check of existence in db I think that this can be placed in validation
Or we can discuss this and choose appropriate way how to deal with this

2024-02-17 17:23 UTC, MishaPolishchuk commented on Streetcode/Streetcode.BLL/MediatR/Streetcode/Fact/Delete/DeleteFactValidation.cs
> +                    CannotFindEntityErrors.CannotFindFactById, dfc.Request.FactId));
Quite a normal idea.
In the validator itself, only properties are processed, and all DB checks are in a separate file.
Yes, this file can be longer than 30-50 lines, but there is no limit. We seem to have no goal of minimizing file sizes.

2024-02-17 17:24 UTC, MishaPolishchuk approved these changes

2024-02-17 17:41 UTC, MrVenik approved these changes

2024-02-17 17:42 UTC, merged