added video block logic
project-studying-dotnet/Streetcode-Admin pull request #173
Opened 2024-03-03 17:04 UTC by Skilskyi

-Created needed DTO for Create, Update, Delete Video
-Added mapping VideoProfile
-Created Command, Handler, Validator for CRUD
-Added endpoints in VideoController
-Added Tests for CRUD

2024-03-03 17:21 UTC, MrVenik commented on Streetcode/Streetcode.BLL/MediatR/Media/Video/Create/CreateVideoValidator.cs
> +    }
It is interesting solution
But you can also use `Uri.TryCreate` method.
Here suggestion from Bing Copilot:
To check whether a string represents a valid HTTP URL in C#, you can use the following methods:

## Using Uri.TryCreate:
C#

```csharp
string uriName = "https://www.example.com"; // Replace with your URL
Uri uriResult;
bool result = Uri.TryCreate(uriName, UriKind.Absolute, out uriResult) &&
              (uriResult.Scheme == Uri.UriSchemeHttp || uriResult.Scheme == Uri.UriSchemeHttps);
```
AI-generated code. Review and use carefully. [More info on FAQ](https://www.bing.com/new#faq).
This method validates both HTTP and HTTPS URLs. [If result is true, the URL is valid](https://stackoverflow.com/questions/7578857/how-to-check-whether-a-string-is-a-valid-http-url)[1](https://stackoverflow.com/questions/7578857/how-to-check-whether-a-string-is-a-valid-http-url).

## Using Uri.IsWellFormedUriString:
C#

```csharp
string uriName = "https://www.example.com"; // Replace with your URL
if (Uri.IsWellFormedUriString(uriName, UriKind.Absolute))
{
    // The URL is valid
}

```
AI-generated code. Review and use carefully. [More info on FAQ](https://www.bing.com/new#faq).
[Note that this method checks if the URL is well-formed (i.e., follows the basic syntax rules), but it doesn’t verify if the URL is active or reachable](https://stackoverflow.com/questions/7578857/how-to-check-whether-a-string-is-a-valid-http-url)[1](https://stackoverflow.com/questions/7578857/how-to-check-whether-a-string-is-a-valid-http-url).
Choose the method that best suits your requirements. Happy coding! 🚀

2024-03-03 17:21 UTC, MrVenik commented on Streetcode/Streetcode.BLL/MediatR/Media/Video/Update/UpdateVideoValidator.cs
Maybe it would be better to separate common validation logic into some extension methods to reduce code duplication.

2024-03-03 17:31 UTC, MrVenik commented on Streetcode/Streetcode.BLL/MediatR/Media/Video/Create/CreateVideoValidator.cs
> +    }
Here how you can check that url locates exactly to youtube: 
```csharp
string host = uri.Host.ToLower(); // Convert host to lowercase for case-insensitive comparison

// Check if the host corresponds to YouTube
return host.Contains("youtube.com") || host.Contains("youtu.be");
```

2024-03-03 17:34 UTC, MrVenik requested changes

2024-03-03 17:34 UTC, MrVenik commented on Streetcode/Streetcode.BLL/MediatR/Media/Video/Update/UpdateVideoValidator.cs
> +                        return video is not null;
Change `StreetcodeRepository` to `VideoRepository`

2024-03-03 17:55 UTC, MrVenik commented on Streetcode/Streetcode.BLL/MediatR/Media/Video/Update/UpdateVideoHandler.cs
> +        return Result.Ok(_mapper.Map<VideoEntity, VideoDto>(video));
Idk why automapper cannot find configuration for this mapping, so I decided to fix this in a simplest way:
```csharp
var response = new VideoDto
{
    Id = video.Id,
    Url = video.Url,
    Description = video.Description,
    StreetcodeId = video.StreetcodeId,
};

return Result.Ok(response);
```

2024-03-04 12:17 UTC, MrVenik approved these changes

2024-03-04 20:23 UTC, SvyatoS1 approved these changes

2024-03-05 05:45 UTC, merged