Task - Ignore sensitive data in the project and create Manual
project-studying-dotnet/Streetcode-Admin pull request #20
Opened 2024-01-25 21:26 UTC by HlibBondarev

**Manual**

1) Add UserSecrets NuGet Package (Microsoft.Extensions.Configuration.UserSecrets) to Project if it is not already installed.

2) Open User Secrets file.
Right click on your project and select the context menu option Manage User Secrets (see pic_1) and add your ConnectionString for local DB to it.  For me it is (see pic_2):

"ConnectionStrings": {
    "DefaultConnection": "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=StreetcodeDb;Integrated Security=True;Connect Timeout=30;"
}

3) Register User Secrets at Start-Up.
Add code (see pic_3) to ConfigureCustom() method in ConfigurationBuilderExtensions class:

.AddUserSecrets<Program>(); // For your local Dev environment only, this won't exist within the Production environment
 
**Conclusion**
You won’t see the created file named secrets.json inside the solution explorer as it’s saved within your roaming data. 
The physical path to your secrets.json file is not included in your code check-in and and is not tracked by Git.

![pic_1](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/56700347/e62b02df-ba4c-499d-8c74-629bf308ed53)

![pic_2](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/56700347/e2cd0646-273f-4c8e-8c9f-f5cf43aac1e7)

![pic_3](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/56700347/a55fa27b-90ab-43b0-8dfe-c19f50293fc0)

2024-01-26 07:18 UTC, vladtymo approved these changes

2024-01-26 07:43 UTC, MrVenik approved these changes

2024-01-26 07:46 UTC, vladtymo requested changes
1 - move sensitive data to user secrets file
2 - remove sensitive data from projects files (appsettings.json, etc)
3 - check vulnerabilities on SonarCloud 
https://sonarcloud.io/project/issues?resolved=false&types=VULNERABILITY&id=project-studying-dotnet_Streetcode-Admin

2024-01-29 07:51 UTC, vladtymo approved these changes

2024-01-29 12:11 UTC, Skilskyi approved these changes

2024-01-29 12:19 UTC, merged