Test: GetTimelineItemByIdHandler
project-studying-dotnet/Streetcode-Admin pull request #49
Opened 2024-01-29 09:50 UTC by Witchdoctor90

## **Summary**
- ShouldReturnSuccessfully test checks if handler return expected item by id
- ShouldReturnNull_NotExistingId test checks if handler return expected error when item not exists

## **Issue**
#34 Closed

2024-01-29 18:49 UTC, MrVenik requested changes
- Remove changes of program.cs and appsettings
- As you added this [commit](https://github.com/project-studying-dotnet/Streetcode-Admin/pull/49/commits/e5f776067bdd623a4cf993a09eec6e30c380fca6) - now you have conflicts

2024-01-30 20:50 UTC, HlibBondarev reviewed
1) Move sensitive data from all appsettigs files into your User Secrets file (see manual - https://github.com/project-studying-dotnet/Streetcode-Admin/pull/20)
2) Merge develop branch into this branch in order to update uppsettings files.
3) After that you can merge this branch into develop

2024-02-16 16:55 UTC, MrVenik approved these changes

2024-02-19 07:11 UTC, SvyatoS1 approved these changes

2024-02-19 07:23 UTC, merged